from sqlalchemy.orm import Session

class tagCRUD():
    def create(db:Session):
        ...
    def update(db:Session):
        ...
    def get(db:Session):
        ...
    def delete(db:Session):
        ...

tags=tagCRUD()