from sqlalchemy.orm import Session

class transazioniCRUD():
    def create(db:Session):
        ...
    def update(db:Session):
        ...
    def get(db:Session):
        ...
    def delete(db:Session):
        ...

transazioni=transazioniCRUD()