"""init

Revision ID: 607e262b1b26
Revises: 
Create Date: 2023-01-27 18:29:20.995424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607e262b1b26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cognome', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abbonamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('giorno', sa.Integer(), nullable=False),
    sa.Column('mese', sa.Integer(), nullable=False),
    sa.Column('inizio', sa.DateTime(), nullable=False),
    sa.Column('fine', sa.DateTime(), nullable=True),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transazione',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('abbonamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abbonamento_id'], ['abbonamento.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_transactions',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transazione.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_transactions')
    op.drop_table('transazione')
    op.drop_table('abbonamento')
    op.drop_table('user')
    op.drop_table('tags')
    # ### end Alembic commands ###
