FROM python:3.11-alpine

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .


# Expose the port that the application will run on
EXPOSE 8000

# migrations
# RUN ["alembic", "upgrade", "head"]
# # Start the application
# CMD ["sh", "docker-entrypoint.sh"]
# CMD ["ping"]